# Generated by Django 3.0.3 on 2020-08-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='ToDo',
        ),
    ]
