# Generated by Django 3.0.3 on 2020-08-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200820_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
